services:
  db-floridos:
    image: postgres:16-alpine
    container_name: floridos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: floridos
      POSTGRES_PASSWORD: floridos123
      POSTGRES_USER: floridos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U floridos"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: floridos-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL:    admin@floridos.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db-floridos:
        condition: service_healthy

volumes:
  postgres_data: