services:
  db-floridos:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=floridos'
      - 'POSTGRES_PASSWORD=floridos123'
      - 'POSTGRES_USER=floridos'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@floridos.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data: